site_name: My Wiki
pages:
    - Home: index.md
    - MkDocs: mkdocs.md
theme:
  name: material
  language: 'ja'
extra_css:
  - "css/extra.css"
markdown_extensions:
  - codehilite:
      linenums: true
  - admonition
extra:
    search:
        language: 'jp'
